#!/bin/bash
install_app() {

###
apt-get --yes upgrade
###

## Install packages
apt-get install --yes ubuntu-standard casper lupin-casper
apt-get install --yes discover laptop-detect os-prober
apt-get install --yes linux-generic
#apt-get install --yes grub2 plymouth-x11
#apt-get install --no-install-recommends network-manager
apt-get install --yes openbox obconf obmenu
apt-get install ubiquity-frontend-gtk

}


install_app
