#!/bin/bash
preparation () {
echo "### preparation"
###
cd /tmp # Заходим в оперативную память
cp /initrd.img ./initrd0.gz # копируем в /tmp initrd.img  
casper-new-uuid /tmp/initrd0.gz /tmp/initrd.gz /tmp/casper-uuid-generic # Создаем файлы initrd.gz и casper-uuid-generic
mkdir /tmp/tmp # создаем папку для временного хранения initramfs
cd ./tmp # входим в нее
gunzip -dc ../initrd.gz | cpio -imvd --no-absolute-filenames # распаковка gz
find . | cpio --quiet --dereference -o -H newc | lzma -7 > ../initrd.lz # упаковка в lz

###


}

copy() {
 echo "### copy initrd.lz"
 [ -d /mnt/hdd ] || mkdir -p /mnt/hdd
 mount /dev/sda1 /mnt/hdd
 cp -r -v /tmp/casper-uuid-generic 	/mnt/hdd/home/serg/zwork/UpWork/Ubstaller/image/casper
 cp -r -v /tmp/initrd.lz 		/mnt/hdd/home/serg/zwork/UpWork/Ubstaller/image/casper
 umount /mnt/hdd
}

clear_tmp() {
 echo "### clear tmp"
 cd /
 rm -rfv /tmp/*
}



preparation
copy
clear_tmp
